package uk.gov.legislation.api.responses;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * A hyperlink to a related fragment with a human‑readable label.
 *
 * <p>Label source: the label is derived from the Atom {@code link/@title}
 * attribute in the source XML (for example, the {@code rel="prev"} or
 * {@code rel="next"} links). That attribute contains a semicolon‑separated
 * list of label components generated by the {@code legislation.xq} script in
 * MarkLogic. We currently use only the first component as the primary display
 * label; additional components may be exposed in the future.</p>
 */
public class LabelledLink {

    @Schema(example = "section/91", description = "Target fragment path relative to the document root")
    public String href;

    @Schema(
        example = "Provision",
        description = "Primary label, taken from the first component of the Atom link @title (components are semicolon‑separated)."
    )
    public String label;

}
